

[Rpc]
timeout = 3.5
server_ip = 172.26.1.247
listen_port = 8888

[Connection]
idle_ms_timeout = 0

[EventLoop]
mutex_queue = 0

sub_event_loop_count = 6

[ThreadPool]
#0=互斥锁队列 1=concurrentQueue_工业级无锁队列 无阻塞 2=blockingConcurrentQueue_ 阻塞 3-其他-无锁队列
start_option = 1

#<=0为取CPU核心数 其他数值为运行的线程数目
thread_count = 0

[RegisterCenter]
ip = 0.0.0.0
port = 8080
ttl_sec = 30

[Trace]
trace_log_name = trace_log


[Http]
; 是否开启chunked编码
chunked = 1

; chunked编码, 超过多少长度就分段发送
chunked_length = 9