

[Rpc]
timeout = 3.5
server_ip = 172.26.1.247
listen_port = 8888

[Connection]
idle_ms_timeout = 0

[RegisterCenter]
ip = 0.0.0.0
port = 8080
ttl_sec = 30

[Trace]
trace_log_name = trace_log


[Http]
; 是否开启chunked编码
chunked = 1

; chunked编码, 超过多少长度就分段发送
chunked_length = 9